basePath: /
definitions:
  models.ContactsDTO:
    properties:
      credly:
        type: string
      email:
        type: string
      github:
        type: string
      linkedin:
        type: string
      name:
        type: string
    type: object
  models.ProjectGroupsDTO:
    properties:
      description:
        type: string
      link_to_project:
        type: string
      project_type:
        type: string
      repositories:
        items:
          $ref: '#/definitions/models.RepositoriesDTO'
        type: array
      title:
        type: string
    type: object
  models.RepositoriesDTO:
    properties:
      description:
        type: string
      link_to_git:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: personal-portfolio documentation for backend
  title: personal-portfolio
  version: "2.0"
paths:
  /contact:
    get:
      consumes:
      - application/json
      description: Get contact information from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ContactsDTO'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get contact information
      tags:
      - contact
  /projects:
    get:
      consumes:
      - application/json
      description: Returns a list of projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/models.ProjectGroupsDTO'
              type: array
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get projects
      tags:
      - projects
swagger: "2.0"
